language: python
python:
- '3.5'
script:
- flake8 .
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: um1Dp37JGUvxYkl4RJq+7Jha03kHhOQbCFa3CRcrsTFHaN5/v1fVuXXK6oAPK2eeoriw4ZA2IUQp+CD5VEhDUSd5Hl/RwA/6jH5I0nRkToE5wUCiOjgZW5amKP+dQJP70DogwTq+CoFYZfg7YE5XxOgrGVROJ3+xJBxr3o8KhmyUGGWFdd0ikbpKeTAiTKuD1xpl82tw/KkVHaWuYpZKe9oJpKcFA47wrMkwDwge36aUBGV8oWcurW3+scfxQR4fNHGHbphgcFQjGxgJrstJd8Z7lMlFVuXPjI4r4xAaTSrNLyQKaf6B2fmX5RASMsBs5y+s1RavgdGnoNn4CkNsb6myFtLQEYSY7y6s9JBCdnvmVER7VCth389YnYDFRVHVxGDwO36THABISR0s0BFohSJyF4SuM1aSlouo2qgMeAjwRgxf5tflq1dIl181TKULsQzH6s7Ua75ZUTzMj+qz7aRZijfmV6u1K23aYuh9gvER5RsA54B83+g62PXb0eI575nJ/4dm2rGjSdob43sTSC4mhyCRqlGk4K0n7PgiZFFXFxpqdbNhHyutSYbcOsYms6DeCb6dNWNltAY3itW0hNDViKZ2u5EcCd3U02167PNyF0J7NTun72wL29wQqawfxIsz6Ujx0/JdKzZQtR1hlI1ugBQ0bGX8wU4gNrnFcgY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/Legos
